


import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;



/**
 *
 * @author Walla Peguero
 */
public class PantallaDeCarga extends javax.swing.JFrame {

    /**
     * Creates new form PantallaDeCarga
     */
    public PantallaDeCarga() {
        initComponents();
        iniciarEfectoLoading();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/LogoJpg.jpg")).getImage()); //Imagen para el soft
        setLocationRelativeTo(null); // Funcion para que la ventana aparezca centralizada 
        
    }
    private void iniciarEfectoLoading() {
    // Crear un hilo para el efecto de puntos
    new Thread(() -> {
        int duracion = 30; // Número de ciclos del efecto
        int delay = 500;   // Tiempo de espera entre cada cambio en milisegundos

        for (int i = 0; i < duracion; i++) {
            // Generar los puntos suspensivos según el ciclo
            String puntos = switch (i % 3) {
                case 0 -> ".";
                case 1 -> "..";
                case 2 -> "...";
                default -> "";
            };    

            // Actualizar el texto del JLabel
            final String textoActualizado = "Loading" + puntos;
            SwingUtilities.invokeLater(() -> lblLoading.setText(textoActualizado));

            // Pausar el hilo
            try {
                Thread.sleep(delay);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }).start();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        lblVector = new javax.swing.JLabel();
        Welcome1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(15, 15, 15));
        jPanel1.setMinimumSize(new java.awt.Dimension(830, 430));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Welcome.setBackground(new java.awt.Color(255, 255, 255));
        Welcome.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        Welcome.setForeground(new java.awt.Color(255, 255, 255));
        Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome.setText("Pet Shop Management ");
        jPanel1.add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 550, 70));

        lblVector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vector.png"))); // NOI18N
        jPanel1.add(lblVector, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 430));

        Welcome1.setBackground(new java.awt.Color(255, 255, 255));
        Welcome1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        Welcome1.setForeground(new java.awt.Color(255, 255, 255));
        Welcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome1.setText("System");
        jPanel1.add(Welcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 200, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Welcome;
    public javax.swing.JLabel Welcome1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblVector;
    // End of variables declaration//GEN-END:variables

}
